### ISSUE TITLE
update user model and yml

### ISSUE THREAD

**Issue by thomaafl** [boolean-uk/team-dev-server-ex-2410-team1#34]
need to add date objects to user model and update yml with the same fields

DateTime in prisma is similar to to new Date('yyyy-mm-dd') in js
```
startDate DateTime?
endtDate DateTIme?
```

In yml file it will look like this:

```
startDate:
    type: string
    format: date-time
    nullable:true
    description: ISO 8601 date-time string
    example: "example-date-string"
```
